CREATE TABLE flights (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_number VARCHAR(50) NOT NULL UNIQUE,
    origin VARCHAR(100) NOT NULL,
    destination VARCHAR(100) NOT NULL,
    departure_time TIMESTAMP NOT NULL,
    total_seats INTEGER NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE seats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_id BIGINT NOT NULL,
    seat_number VARCHAR(10) NOT NULL,
    row_number INTEGER NOT NULL,
    column_letter VARCHAR(5) NOT NULL,
    state VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
    version BIGINT DEFAULT 0,
    CONSTRAINT uk_seat_flight_number UNIQUE (flight_id, seat_number),
    CONSTRAINT fk_seat_flight FOREIGN KEY (flight_id) REFERENCES flights(id)
);

CREATE INDEX idx_seat_flight ON seats(flight_id);
CREATE INDEX idx_seat_flight_number ON seats(flight_id, seat_number);

CREATE TABLE seat_reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seat_id BIGINT NOT NULL,
    flight_id BIGINT NOT NULL,
    passenger_id VARCHAR(100) NOT NULL,
    state VARCHAR(20) NOT NULL,
    held_at TIMESTAMP,
    held_until TIMESTAMP,
    confirmed_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_reservation_seat FOREIGN KEY (seat_id) REFERENCES seats(id),
    CONSTRAINT fk_reservation_flight FOREIGN KEY (flight_id) REFERENCES flights(id)
);

CREATE INDEX idx_reservation_seat ON seat_reservations(seat_id);
CREATE INDEX idx_reservation_held_until ON seat_reservations(held_until);
CREATE INDEX idx_reservation_passenger ON seat_reservations(passenger_id);
