CREATE TABLE check_ins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_id BIGINT NOT NULL,
    passenger_id VARCHAR(100) NOT NULL,
    reservation_id BIGINT,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    completed_at TIMESTAMP,
    CONSTRAINT fk_checkin_flight FOREIGN KEY (flight_id) REFERENCES flights(id)
);

CREATE INDEX idx_checkin_passenger ON check_ins(passenger_id);
CREATE INDEX idx_checkin_flight ON check_ins(flight_id);

CREATE TABLE baggage_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    check_in_id BIGINT NOT NULL,
    baggage_id VARCHAR(100) NOT NULL,
    weight_kg DECIMAL(10,2) NOT NULL,
    fee_amount DECIMAL(10,2),
    paid BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP,
    CONSTRAINT fk_baggage_checkin FOREIGN KEY (check_in_id) REFERENCES check_ins(id)
);

CREATE INDEX idx_baggage_checkin ON baggage_records(check_in_id);
