CREATE TABLE waitlist_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_id BIGINT NOT NULL,
    passenger_id VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL,
    reservation_id BIGINT,
    created_at TIMESTAMP,
    assigned_at TIMESTAMP,
    CONSTRAINT fk_waitlist_flight FOREIGN KEY (flight_id) REFERENCES flights(id)
);

CREATE INDEX idx_waitlist_flight_status ON waitlist_entries(flight_id, status);
CREATE INDEX idx_waitlist_created ON waitlist_entries(created_at);
