CREATE TABLE access_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id VARCHAR(100) NOT NULL,
    flight_id BIGINT NOT NULL,
    accessed_at TIMESTAMP NOT NULL,
    endpoint VARCHAR(255)
);

CREATE INDEX idx_access_source_time ON access_logs(source_id, accessed_at);

CREATE TABLE abuse_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id VARCHAR(100) NOT NULL,
    access_count INTEGER,
    window_seconds INTEGER,
    detected_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_abuse_source ON abuse_events(source_id);
CREATE INDEX idx_abuse_time ON abuse_events(detected_at);
